apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efs-csi-app
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    
    path: aws-efs-csi-driver
    helm:
      parameters:
        - name: cluster.name
          value: {{ .Values.cluster.name }}
        - name: cluster.region
          value: {{ .Values.cluster.awsRegion }}

  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    validate: true
