apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efs-csi-app
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source: 
    repoURL: https://github.com/azzy123/k8s-bootstrap.git
    targetRevision: HEAD
    path: aws-efs-csi-driver
    helm:
      parameters:
        - name: cluster.name
          value: "test-staging"
        - name: cluster.region
          value: "us-east-2"

  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    validate: true
